### ISSUE TITLE
Cancel button for upcoming appointments has text "cancel" spelt incorrectly

### ISSUE THREAD

**Issue by JacenSolo95** [prrathnayake/myHealthSystem#4]
Text should be spelt "cancel" not "cancle"
![photo_2023-01-22_16-39-09](https://user-images.githubusercontent.com/67223286/213912744-117a11a9-eb21-4768-af9b-d2de65e5d1b4.jpg)

**Comment by prrathnayake** [comment]
fixed

**Comment by JacenSolo95** [comment]
Cancel is spelt incorrectly in the appointment status and error toast message
![photo_2023-01-22_18-18-25](https://user-images.githubusercontent.com/67223286/213916613-d790a274-43ec-453f-8f80-2c9501124b81.jpg)

**Comment by prrathnayake** [comment]
fixed
