### ISSUE TITLE
Change error text when doctor isn't available to say "Doctor isn't available on [day]"

### ISSUE THREAD

**Issue by JacenSolo95** [prrathnayake/myHealthSystem#7]
Change error text when appointment is set to day when doctor isn't available to say "Doctor isn't available on [day]" instead of "Doctor doesn't available in [day]"
![photo_2023-01-22_19-04-53](https://user-images.githubusercontent.com/67223286/213918665-e44a5dc4-2465-4e75-8454-92efb48b104c.jpg)

**Comment by prrathnayake** [comment]
fixed
