### ISSUE TITLE
Change error text when doctor isn't available to say "Doctor isn't available from [start time] to [end time]"

### ISSUE THREAD

**Issue by JacenSolo95** [prrathnayake/myHealthSystem#8]
Change error text when appointment is set to time doctor isn't available to say "Doctor isn't available from [start time] to [end time]" instead of "Doctor only available at [available start time] to [available end time]"
![photo_2023-01-22_19-30-45](https://user-images.githubusercontent.com/67223286/213919784-91eaf5b9-8c45-42f9-b649-5a3ac865cb57.jpg)

**Comment by prrathnayake** [comment]
fixed
